travis:
  secure:
    BINSTAR_TOKEN: R+HTthA0dvjfun3u6QyFP6sErjA1teFY9k5fvERtM74jFihyWQvld2kHkEzzieOLuh2lmV/asPgxcZkKcZaQgIuaPP2MgpfK4Zw4PyS6553ZPb4MXg+1RlNRUKcrRe3PQRVZM49yjlyvqO+uAgTKK6RmK2kqnSAAXwGaKfOqPuDZXW4IlSkWOEFnOJ97m4ZD6+yoqzEgxI91iJQg4SlI0FvXLb0CHzcPCx30qOI69qkc7YyVz52qcvGlbCnU/Y5idAoQGNJ2bcqSs/Ba6gEfZv7abLfYnCFN96spBL2dFj6KMa3fGo/GHIzXJHVFgkAIevzuvFhX1LnKCV2PLqbxu9PrixZ1WCRRGj53TDzUd8WvXgkKOYCWiMNxtk53pGEG4FiNnR8PETaBc4qMNPKAGl9/DDMa7tq4nSsIzX+rdfNFFPLNv4ifUKiUErj4Q+A4j7ze9fLJtYdcMwKFUz0KzPKJjJvtMZacRUDk5T85GEkblECKtKaClrIpXhJg1aQ8+EFw41B8Y/8T3/pfns9P4rPYo09N8bsaBSES8fspUsHTuwLuVS7qYFmGw5SsCu2mhI9NIO3HEQhNUK2z19Oj7bYXP7PNYFfbM6z0RqA4Fh9M7RhH54X+8kBAi47o1oGkEkbi3haxsWNCKX9IkpOYLN3otbH1b+Iz9/UM3nobRXk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
